export const USER = {
	LOAD: {
		SUCCESS: 'USER_LOAD_SUCCESS'
	},
	GET: {
		SUCCESS: 'USER_GET_SUCCESS'
	},
	CREATE: {
		SUCCESS: 'USER_CREATE_SUCCESS'
	},
	DELETE: {
		SUCCESS: 'USER_DELETE_SUCCESS'
	},
	UPDATE: {
		SUCCESS: 'USER_UPDATE_SUCCESS'
	}
};